FROM node:21

ENV NODE_ENV development

WORKDIR /usr/src/app

COPY ["package.json", "package-lock.json", "/usr/src/app/"]

RUN npm install

COPY . .

EXPOSE 5173
EXPOSE 24678

CMD ["npm", "run", "dev"]